### ISSUE TITLE
File / Folder を置き換える

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#2773]
## 概要
File / Folder について、CakePHP5で削除されるため、別の仕組みに置き換える

## TODO
- [ ] `dev-#2773` ブランチをチェックアウト
- [ ] PhpStormのコードインスペクションで `plugins` ディレクトリを指定して利用箇所を洗い出す
- [ ] PHP → 一般 → 非推奨 で利用箇所を確認
- [ ] BcFolder / BcFile を利用し非推奨を書き換える
- [ ] BcFolder / BcFile に足りないメソッドがあれば実装しテストも書く
- [ ] ユニットテストで問題がないか確認
- [ ] ブラウザでのテストも実施する
- [ ] dev-5 ではなっく、`dev-#2773` ブランチにプルリクエストを送る（１ファイルずつお願いします）

## 参考情報
- 対象箇所は300箇所弱
- ユニットテストでの利用箇所から書き換える

## コードインスペクションの画面
<img width="1578" alt="スクリーンショット 2023-10-01 16 42 35" src="https://github.com/baserproject/basercms/assets/90106/f539ef4b-1872-4f7f-8693-d00a07a71d6f">

<img width="1578" alt="スクリーンショット 2023-10-01 16 43 17" src="https://github.com/baserproject/basercms/assets/90106/39feb986-1f28-4066-ae2b-498cc65abe2d">

baserCMS version : 5.0.5

**Comment by ryuring** [comment]
@nghiem-mb CakePHP5より、File / Folder クラスが削除となります。こちらについて、BcFile / BcFolder クラスに書き換えをお願いします。かなりの量があり、影響が大きいクラスですので、焦らず、注意深くお願いします。

**Comment by ryuring** [comment]
dev-cake5 ブランチにて解決済
@nghiem-mb ありがとうございました！
