### ISSUE TITLE
ブログカテゴリアーカイブページや年別一覧ページなどでカテゴリや記事タイトルがパンくずやtitleタグに正しく反映されない問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3099]
## 概要
ブログindexページ以外で
`$this->BcBaser->getCrumbs()`
や
`$this->BcHtml->getStripCrumbs();`
を使っても、
パンくずの最後がブログコンテンツ名になってしまいます。
また、タイトルタグもコンテンツ名が最初に来てしまいます。

上記と関連して
ブログカテゴリアーカイブページや年別一覧ページなどで
$this->Blog->getTitle()
を使用すると
`Warning (2) : Attempt to read property “title” on null`
となってしまいます。

baserCMS version : 5.0.8
 
## TODO
- [ ] bc_baser_core  BcBaserHelper.php  getContentsTitle() の調整
- [ ] bc_Blog
   - [ ] BlogHelper.php getTitle() の調整
   - [ ] BcBlogBaserHelper.php methods() の追加

 
## 備考
